; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
data_dir = .littlefs

[esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram = enabled
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.extra_flags = -DBOARD_HAS_PSRAM
monitor_speed = 115200
build_flags = -Iinclude
board_build.filesystem = littlefs
upload_protocol = esptool 

[sketch]
build_src_filter = +<*> -<.git/> -<.svn/> -<envs/*> +<envs/${PIOENV}/*> ; Build only the sources for the active environment under src/envs/${PIOENV}/

[libraries]
lib_deps = 
    https://github.com/Links2004/arduinoWebSockets.git#2.7.2
    https://github.com/pschatzmann/arduino-audio-tools.git#v1.2.4
    fastled/FastLED
    bblanchon/ArduinoJson

[env:voice_websocket]
extends = esp32s3, sketch, libraries

[env:test_queue]
extends = esp32s3, sketch
