// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PUMPKIN_PUMPKIN_PROTOCOL_H_
#define FLATBUFFERS_GENERATED_PUMPKIN_PUMPKIN_PROTOCOL_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

namespace Pumpkin {
namespace Protocol {

struct StartAudioStream;
struct StartAudioStreamBuilder;

struct StopAudioStream;
struct StopAudioStreamBuilder;

struct PlayShow;
struct PlayShowBuilder;

struct AudioChunk;
struct AudioChunkBuilder;

struct ResetAudio;
struct ResetAudioBuilder;

struct GetVolume;
struct GetVolumeBuilder;

struct AdjustVolume;
struct AdjustVolumeBuilder;

struct ListAudioFiles;
struct ListAudioFilesBuilder;

struct PlayAudioFile;
struct PlayAudioFileBuilder;

struct BeginAudioUpload;
struct BeginAudioUploadBuilder;

struct AudioUploadChunk;
struct AudioUploadChunkBuilder;

struct FinishAudioUpload;
struct FinishAudioUploadBuilder;

struct CancelAudioUpload;
struct CancelAudioUploadBuilder;

struct ClientMessage;
struct ClientMessageBuilder;

struct Success;
struct SuccessBuilder;

struct Error;
struct ErrorBuilder;

struct Volume;
struct VolumeBuilder;

struct AudioFile;
struct AudioFileBuilder;

struct AudioFileList;
struct AudioFileListBuilder;

struct ServerMessage;
struct ServerMessageBuilder;

struct Message;
struct MessageBuilder;

enum ClientPayload : uint8_t {
  ClientPayload_NONE = 0,
  ClientPayload_StartAudioStream = 1,
  ClientPayload_StopAudioStream = 2,
  ClientPayload_PlayShow = 3,
  ClientPayload_AudioChunk = 4,
  ClientPayload_ResetAudio = 5,
  ClientPayload_GetVolume = 6,
  ClientPayload_AdjustVolume = 7,
  ClientPayload_ListAudioFiles = 8,
  ClientPayload_PlayAudioFile = 9,
  ClientPayload_BeginAudioUpload = 10,
  ClientPayload_AudioUploadChunk = 11,
  ClientPayload_FinishAudioUpload = 12,
  ClientPayload_CancelAudioUpload = 13,
  ClientPayload_MIN = ClientPayload_NONE,
  ClientPayload_MAX = ClientPayload_CancelAudioUpload
};

inline const ClientPayload (&EnumValuesClientPayload())[14] {
  static const ClientPayload values[] = {
    ClientPayload_NONE,
    ClientPayload_StartAudioStream,
    ClientPayload_StopAudioStream,
    ClientPayload_PlayShow,
    ClientPayload_AudioChunk,
    ClientPayload_ResetAudio,
    ClientPayload_GetVolume,
    ClientPayload_AdjustVolume,
    ClientPayload_ListAudioFiles,
    ClientPayload_PlayAudioFile,
    ClientPayload_BeginAudioUpload,
    ClientPayload_AudioUploadChunk,
    ClientPayload_FinishAudioUpload,
    ClientPayload_CancelAudioUpload
  };
  return values;
}

inline const char * const *EnumNamesClientPayload() {
  static const char * const names[15] = {
    "NONE",
    "StartAudioStream",
    "StopAudioStream",
    "PlayShow",
    "AudioChunk",
    "ResetAudio",
    "GetVolume",
    "AdjustVolume",
    "ListAudioFiles",
    "PlayAudioFile",
    "BeginAudioUpload",
    "AudioUploadChunk",
    "FinishAudioUpload",
    "CancelAudioUpload",
    nullptr
  };
  return names;
}

inline const char *EnumNameClientPayload(ClientPayload e) {
  if (::flatbuffers::IsOutRange(e, ClientPayload_NONE, ClientPayload_CancelAudioUpload)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesClientPayload()[index];
}

template<typename T> struct ClientPayloadTraits {
  static const ClientPayload enum_value = ClientPayload_NONE;
};

template<> struct ClientPayloadTraits<Pumpkin::Protocol::StartAudioStream> {
  static const ClientPayload enum_value = ClientPayload_StartAudioStream;
};

template<> struct ClientPayloadTraits<Pumpkin::Protocol::StopAudioStream> {
  static const ClientPayload enum_value = ClientPayload_StopAudioStream;
};

template<> struct ClientPayloadTraits<Pumpkin::Protocol::PlayShow> {
  static const ClientPayload enum_value = ClientPayload_PlayShow;
};

template<> struct ClientPayloadTraits<Pumpkin::Protocol::AudioChunk> {
  static const ClientPayload enum_value = ClientPayload_AudioChunk;
};

template<> struct ClientPayloadTraits<Pumpkin::Protocol::ResetAudio> {
  static const ClientPayload enum_value = ClientPayload_ResetAudio;
};

template<> struct ClientPayloadTraits<Pumpkin::Protocol::GetVolume> {
  static const ClientPayload enum_value = ClientPayload_GetVolume;
};

template<> struct ClientPayloadTraits<Pumpkin::Protocol::AdjustVolume> {
  static const ClientPayload enum_value = ClientPayload_AdjustVolume;
};

template<> struct ClientPayloadTraits<Pumpkin::Protocol::ListAudioFiles> {
  static const ClientPayload enum_value = ClientPayload_ListAudioFiles;
};

template<> struct ClientPayloadTraits<Pumpkin::Protocol::PlayAudioFile> {
  static const ClientPayload enum_value = ClientPayload_PlayAudioFile;
};

template<> struct ClientPayloadTraits<Pumpkin::Protocol::BeginAudioUpload> {
  static const ClientPayload enum_value = ClientPayload_BeginAudioUpload;
};

template<> struct ClientPayloadTraits<Pumpkin::Protocol::AudioUploadChunk> {
  static const ClientPayload enum_value = ClientPayload_AudioUploadChunk;
};

template<> struct ClientPayloadTraits<Pumpkin::Protocol::FinishAudioUpload> {
  static const ClientPayload enum_value = ClientPayload_FinishAudioUpload;
};

template<> struct ClientPayloadTraits<Pumpkin::Protocol::CancelAudioUpload> {
  static const ClientPayload enum_value = ClientPayload_CancelAudioUpload;
};

bool VerifyClientPayload(::flatbuffers::Verifier &verifier, const void *obj, ClientPayload type);
bool VerifyClientPayloadVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

enum ErrorCode : uint8_t {
  ErrorCode_UNKNOWN = 0,
  ErrorCode_INVALID_MESSAGE = 1,
  ErrorCode_UNSUPPORTED_MESSAGE = 2,
  ErrorCode_INVALID_ARGUMENT = 3,
  ErrorCode_MIN = ErrorCode_UNKNOWN,
  ErrorCode_MAX = ErrorCode_INVALID_ARGUMENT
};

inline const ErrorCode (&EnumValuesErrorCode())[4] {
  static const ErrorCode values[] = {
    ErrorCode_UNKNOWN,
    ErrorCode_INVALID_MESSAGE,
    ErrorCode_UNSUPPORTED_MESSAGE,
    ErrorCode_INVALID_ARGUMENT
  };
  return values;
}

inline const char * const *EnumNamesErrorCode() {
  static const char * const names[5] = {
    "UNKNOWN",
    "INVALID_MESSAGE",
    "UNSUPPORTED_MESSAGE",
    "INVALID_ARGUMENT",
    nullptr
  };
  return names;
}

inline const char *EnumNameErrorCode(ErrorCode e) {
  if (::flatbuffers::IsOutRange(e, ErrorCode_UNKNOWN, ErrorCode_INVALID_ARGUMENT)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesErrorCode()[index];
}

enum ServerPayload : uint8_t {
  ServerPayload_NONE = 0,
  ServerPayload_Success = 1,
  ServerPayload_Error = 2,
  ServerPayload_Volume = 3,
  ServerPayload_AudioFileList = 4,
  ServerPayload_MIN = ServerPayload_NONE,
  ServerPayload_MAX = ServerPayload_AudioFileList
};

inline const ServerPayload (&EnumValuesServerPayload())[5] {
  static const ServerPayload values[] = {
    ServerPayload_NONE,
    ServerPayload_Success,
    ServerPayload_Error,
    ServerPayload_Volume,
    ServerPayload_AudioFileList
  };
  return values;
}

inline const char * const *EnumNamesServerPayload() {
  static const char * const names[6] = {
    "NONE",
    "Success",
    "Error",
    "Volume",
    "AudioFileList",
    nullptr
  };
  return names;
}

inline const char *EnumNameServerPayload(ServerPayload e) {
  if (::flatbuffers::IsOutRange(e, ServerPayload_NONE, ServerPayload_AudioFileList)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesServerPayload()[index];
}

template<typename T> struct ServerPayloadTraits {
  static const ServerPayload enum_value = ServerPayload_NONE;
};

template<> struct ServerPayloadTraits<Pumpkin::Protocol::Success> {
  static const ServerPayload enum_value = ServerPayload_Success;
};

template<> struct ServerPayloadTraits<Pumpkin::Protocol::Error> {
  static const ServerPayload enum_value = ServerPayload_Error;
};

template<> struct ServerPayloadTraits<Pumpkin::Protocol::Volume> {
  static const ServerPayload enum_value = ServerPayload_Volume;
};

template<> struct ServerPayloadTraits<Pumpkin::Protocol::AudioFileList> {
  static const ServerPayload enum_value = ServerPayload_AudioFileList;
};

bool VerifyServerPayload(::flatbuffers::Verifier &verifier, const void *obj, ServerPayload type);
bool VerifyServerPayloadVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

enum MessageBody : uint8_t {
  MessageBody_NONE = 0,
  MessageBody_ClientMessage = 1,
  MessageBody_ServerMessage = 2,
  MessageBody_MIN = MessageBody_NONE,
  MessageBody_MAX = MessageBody_ServerMessage
};

inline const MessageBody (&EnumValuesMessageBody())[3] {
  static const MessageBody values[] = {
    MessageBody_NONE,
    MessageBody_ClientMessage,
    MessageBody_ServerMessage
  };
  return values;
}

inline const char * const *EnumNamesMessageBody() {
  static const char * const names[4] = {
    "NONE",
    "ClientMessage",
    "ServerMessage",
    nullptr
  };
  return names;
}

inline const char *EnumNameMessageBody(MessageBody e) {
  if (::flatbuffers::IsOutRange(e, MessageBody_NONE, MessageBody_ServerMessage)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMessageBody()[index];
}

template<typename T> struct MessageBodyTraits {
  static const MessageBody enum_value = MessageBody_NONE;
};

template<> struct MessageBodyTraits<Pumpkin::Protocol::ClientMessage> {
  static const MessageBody enum_value = MessageBody_ClientMessage;
};

template<> struct MessageBodyTraits<Pumpkin::Protocol::ServerMessage> {
  static const MessageBody enum_value = MessageBody_ServerMessage;
};

bool VerifyMessageBody(::flatbuffers::Verifier &verifier, const void *obj, MessageBody type);
bool VerifyMessageBodyVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct StartAudioStream FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StartAudioStreamBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct StartAudioStreamBuilder {
  typedef StartAudioStream Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit StartAudioStreamBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StartAudioStream> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StartAudioStream>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<StartAudioStream> CreateStartAudioStream(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  StartAudioStreamBuilder builder_(_fbb);
  return builder_.Finish();
}

struct StopAudioStream FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StopAudioStreamBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct StopAudioStreamBuilder {
  typedef StopAudioStream Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit StopAudioStreamBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StopAudioStream> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StopAudioStream>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<StopAudioStream> CreateStopAudioStream(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  StopAudioStreamBuilder builder_(_fbb);
  return builder_.Finish();
}

struct PlayShow FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PlayShowBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SHOW_ID = 4
  };
  uint16_t show_id() const {
    return GetField<uint16_t>(VT_SHOW_ID, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_SHOW_ID, 2) &&
           verifier.EndTable();
  }
};

struct PlayShowBuilder {
  typedef PlayShow Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_show_id(uint16_t show_id) {
    fbb_.AddElement<uint16_t>(PlayShow::VT_SHOW_ID, show_id, 0);
  }
  explicit PlayShowBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PlayShow> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PlayShow>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PlayShow> CreatePlayShow(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t show_id = 0) {
  PlayShowBuilder builder_(_fbb);
  builder_.add_show_id(show_id);
  return builder_.Finish();
}

struct AudioChunk FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AudioChunkBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PCM_S16LE = 4
  };
  const ::flatbuffers::Vector<uint8_t> *pcm_s16le() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_PCM_S16LE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_PCM_S16LE) &&
           verifier.VerifyVector(pcm_s16le()) &&
           verifier.EndTable();
  }
};

struct AudioChunkBuilder {
  typedef AudioChunk Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_pcm_s16le(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> pcm_s16le) {
    fbb_.AddOffset(AudioChunk::VT_PCM_S16LE, pcm_s16le);
  }
  explicit AudioChunkBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AudioChunk> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AudioChunk>(end);
    fbb_.Required(o, AudioChunk::VT_PCM_S16LE);
    return o;
  }
};

inline ::flatbuffers::Offset<AudioChunk> CreateAudioChunk(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> pcm_s16le = 0) {
  AudioChunkBuilder builder_(_fbb);
  builder_.add_pcm_s16le(pcm_s16le);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<AudioChunk> CreateAudioChunkDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *pcm_s16le = nullptr) {
  auto pcm_s16le__ = pcm_s16le ? _fbb.CreateVector<uint8_t>(*pcm_s16le) : 0;
  return Pumpkin::Protocol::CreateAudioChunk(
      _fbb,
      pcm_s16le__);
}

struct ResetAudio FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ResetAudioBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct ResetAudioBuilder {
  typedef ResetAudio Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit ResetAudioBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ResetAudio> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ResetAudio>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ResetAudio> CreateResetAudio(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  ResetAudioBuilder builder_(_fbb);
  return builder_.Finish();
}

struct GetVolume FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GetVolumeBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct GetVolumeBuilder {
  typedef GetVolume Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit GetVolumeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<GetVolume> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<GetVolume>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<GetVolume> CreateGetVolume(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  GetVolumeBuilder builder_(_fbb);
  return builder_.Finish();
}

struct AdjustVolume FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AdjustVolumeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DELTA = 4
  };
  float delta() const {
    return GetField<float>(VT_DELTA, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_DELTA, 4) &&
           verifier.EndTable();
  }
};

struct AdjustVolumeBuilder {
  typedef AdjustVolume Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_delta(float delta) {
    fbb_.AddElement<float>(AdjustVolume::VT_DELTA, delta, 0.0f);
  }
  explicit AdjustVolumeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AdjustVolume> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AdjustVolume>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<AdjustVolume> CreateAdjustVolume(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float delta = 0.0f) {
  AdjustVolumeBuilder builder_(_fbb);
  builder_.add_delta(delta);
  return builder_.Finish();
}

struct ListAudioFiles FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ListAudioFilesBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct ListAudioFilesBuilder {
  typedef ListAudioFiles Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit ListAudioFilesBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ListAudioFiles> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ListAudioFiles>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ListAudioFiles> CreateListAudioFiles(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  ListAudioFilesBuilder builder_(_fbb);
  return builder_.Finish();
}

struct PlayAudioFile FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PlayAudioFileBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           verifier.EndTable();
  }
};

struct PlayAudioFileBuilder {
  typedef PlayAudioFile Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(PlayAudioFile::VT_NAME, name);
  }
  explicit PlayAudioFileBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PlayAudioFile> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PlayAudioFile>(end);
    fbb_.Required(o, PlayAudioFile::VT_NAME);
    return o;
  }
};

inline ::flatbuffers::Offset<PlayAudioFile> CreatePlayAudioFile(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0) {
  PlayAudioFileBuilder builder_(_fbb);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<PlayAudioFile> CreatePlayAudioFileDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return Pumpkin::Protocol::CreatePlayAudioFile(
      _fbb,
      name__);
}

struct BeginAudioUpload FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BeginAudioUploadBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_SIZE = 6
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  uint32_t size() const {
    return GetField<uint32_t>(VT_SIZE, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<uint32_t>(verifier, VT_SIZE, 4) &&
           verifier.EndTable();
  }
};

struct BeginAudioUploadBuilder {
  typedef BeginAudioUpload Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(BeginAudioUpload::VT_NAME, name);
  }
  void add_size(uint32_t size) {
    fbb_.AddElement<uint32_t>(BeginAudioUpload::VT_SIZE, size, 0);
  }
  explicit BeginAudioUploadBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BeginAudioUpload> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BeginAudioUpload>(end);
    fbb_.Required(o, BeginAudioUpload::VT_NAME);
    return o;
  }
};

inline ::flatbuffers::Offset<BeginAudioUpload> CreateBeginAudioUpload(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    uint32_t size = 0) {
  BeginAudioUploadBuilder builder_(_fbb);
  builder_.add_size(size);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<BeginAudioUpload> CreateBeginAudioUploadDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    uint32_t size = 0) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return Pumpkin::Protocol::CreateBeginAudioUpload(
      _fbb,
      name__,
      size);
}

struct AudioUploadChunk FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AudioUploadChunkBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BYTES = 4
  };
  const ::flatbuffers::Vector<uint8_t> *bytes() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_BYTES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_BYTES) &&
           verifier.VerifyVector(bytes()) &&
           verifier.EndTable();
  }
};

struct AudioUploadChunkBuilder {
  typedef AudioUploadChunk Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_bytes(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> bytes) {
    fbb_.AddOffset(AudioUploadChunk::VT_BYTES, bytes);
  }
  explicit AudioUploadChunkBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AudioUploadChunk> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AudioUploadChunk>(end);
    fbb_.Required(o, AudioUploadChunk::VT_BYTES);
    return o;
  }
};

inline ::flatbuffers::Offset<AudioUploadChunk> CreateAudioUploadChunk(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> bytes = 0) {
  AudioUploadChunkBuilder builder_(_fbb);
  builder_.add_bytes(bytes);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<AudioUploadChunk> CreateAudioUploadChunkDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *bytes = nullptr) {
  auto bytes__ = bytes ? _fbb.CreateVector<uint8_t>(*bytes) : 0;
  return Pumpkin::Protocol::CreateAudioUploadChunk(
      _fbb,
      bytes__);
}

struct FinishAudioUpload FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef FinishAudioUploadBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct FinishAudioUploadBuilder {
  typedef FinishAudioUpload Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit FinishAudioUploadBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<FinishAudioUpload> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<FinishAudioUpload>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<FinishAudioUpload> CreateFinishAudioUpload(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  FinishAudioUploadBuilder builder_(_fbb);
  return builder_.Finish();
}

struct CancelAudioUpload FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CancelAudioUploadBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct CancelAudioUploadBuilder {
  typedef CancelAudioUpload Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit CancelAudioUploadBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CancelAudioUpload> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CancelAudioUpload>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CancelAudioUpload> CreateCancelAudioUpload(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  CancelAudioUploadBuilder builder_(_fbb);
  return builder_.Finish();
}

struct ClientMessage FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientMessageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_REQUEST_ID = 4,
    VT_PAYLOAD_TYPE = 6,
    VT_PAYLOAD = 8
  };
  uint32_t request_id() const {
    return GetField<uint32_t>(VT_REQUEST_ID, 0);
  }
  Pumpkin::Protocol::ClientPayload payload_type() const {
    return static_cast<Pumpkin::Protocol::ClientPayload>(GetField<uint8_t>(VT_PAYLOAD_TYPE, 0));
  }
  const void *payload() const {
    return GetPointer<const void *>(VT_PAYLOAD);
  }
  template<typename T> const T *payload_as() const;
  const Pumpkin::Protocol::StartAudioStream *payload_as_StartAudioStream() const {
    return payload_type() == Pumpkin::Protocol::ClientPayload_StartAudioStream ? static_cast<const Pumpkin::Protocol::StartAudioStream *>(payload()) : nullptr;
  }
  const Pumpkin::Protocol::StopAudioStream *payload_as_StopAudioStream() const {
    return payload_type() == Pumpkin::Protocol::ClientPayload_StopAudioStream ? static_cast<const Pumpkin::Protocol::StopAudioStream *>(payload()) : nullptr;
  }
  const Pumpkin::Protocol::PlayShow *payload_as_PlayShow() const {
    return payload_type() == Pumpkin::Protocol::ClientPayload_PlayShow ? static_cast<const Pumpkin::Protocol::PlayShow *>(payload()) : nullptr;
  }
  const Pumpkin::Protocol::AudioChunk *payload_as_AudioChunk() const {
    return payload_type() == Pumpkin::Protocol::ClientPayload_AudioChunk ? static_cast<const Pumpkin::Protocol::AudioChunk *>(payload()) : nullptr;
  }
  const Pumpkin::Protocol::ResetAudio *payload_as_ResetAudio() const {
    return payload_type() == Pumpkin::Protocol::ClientPayload_ResetAudio ? static_cast<const Pumpkin::Protocol::ResetAudio *>(payload()) : nullptr;
  }
  const Pumpkin::Protocol::GetVolume *payload_as_GetVolume() const {
    return payload_type() == Pumpkin::Protocol::ClientPayload_GetVolume ? static_cast<const Pumpkin::Protocol::GetVolume *>(payload()) : nullptr;
  }
  const Pumpkin::Protocol::AdjustVolume *payload_as_AdjustVolume() const {
    return payload_type() == Pumpkin::Protocol::ClientPayload_AdjustVolume ? static_cast<const Pumpkin::Protocol::AdjustVolume *>(payload()) : nullptr;
  }
  const Pumpkin::Protocol::ListAudioFiles *payload_as_ListAudioFiles() const {
    return payload_type() == Pumpkin::Protocol::ClientPayload_ListAudioFiles ? static_cast<const Pumpkin::Protocol::ListAudioFiles *>(payload()) : nullptr;
  }
  const Pumpkin::Protocol::PlayAudioFile *payload_as_PlayAudioFile() const {
    return payload_type() == Pumpkin::Protocol::ClientPayload_PlayAudioFile ? static_cast<const Pumpkin::Protocol::PlayAudioFile *>(payload()) : nullptr;
  }
  const Pumpkin::Protocol::BeginAudioUpload *payload_as_BeginAudioUpload() const {
    return payload_type() == Pumpkin::Protocol::ClientPayload_BeginAudioUpload ? static_cast<const Pumpkin::Protocol::BeginAudioUpload *>(payload()) : nullptr;
  }
  const Pumpkin::Protocol::AudioUploadChunk *payload_as_AudioUploadChunk() const {
    return payload_type() == Pumpkin::Protocol::ClientPayload_AudioUploadChunk ? static_cast<const Pumpkin::Protocol::AudioUploadChunk *>(payload()) : nullptr;
  }
  const Pumpkin::Protocol::FinishAudioUpload *payload_as_FinishAudioUpload() const {
    return payload_type() == Pumpkin::Protocol::ClientPayload_FinishAudioUpload ? static_cast<const Pumpkin::Protocol::FinishAudioUpload *>(payload()) : nullptr;
  }
  const Pumpkin::Protocol::CancelAudioUpload *payload_as_CancelAudioUpload() const {
    return payload_type() == Pumpkin::Protocol::ClientPayload_CancelAudioUpload ? static_cast<const Pumpkin::Protocol::CancelAudioUpload *>(payload()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_REQUEST_ID, 4) &&
           VerifyField<uint8_t>(verifier, VT_PAYLOAD_TYPE, 1) &&
           VerifyOffsetRequired(verifier, VT_PAYLOAD) &&
           VerifyClientPayload(verifier, payload(), payload_type()) &&
           verifier.EndTable();
  }
};

template<> inline const Pumpkin::Protocol::StartAudioStream *ClientMessage::payload_as<Pumpkin::Protocol::StartAudioStream>() const {
  return payload_as_StartAudioStream();
}

template<> inline const Pumpkin::Protocol::StopAudioStream *ClientMessage::payload_as<Pumpkin::Protocol::StopAudioStream>() const {
  return payload_as_StopAudioStream();
}

template<> inline const Pumpkin::Protocol::PlayShow *ClientMessage::payload_as<Pumpkin::Protocol::PlayShow>() const {
  return payload_as_PlayShow();
}

template<> inline const Pumpkin::Protocol::AudioChunk *ClientMessage::payload_as<Pumpkin::Protocol::AudioChunk>() const {
  return payload_as_AudioChunk();
}

template<> inline const Pumpkin::Protocol::ResetAudio *ClientMessage::payload_as<Pumpkin::Protocol::ResetAudio>() const {
  return payload_as_ResetAudio();
}

template<> inline const Pumpkin::Protocol::GetVolume *ClientMessage::payload_as<Pumpkin::Protocol::GetVolume>() const {
  return payload_as_GetVolume();
}

template<> inline const Pumpkin::Protocol::AdjustVolume *ClientMessage::payload_as<Pumpkin::Protocol::AdjustVolume>() const {
  return payload_as_AdjustVolume();
}

template<> inline const Pumpkin::Protocol::ListAudioFiles *ClientMessage::payload_as<Pumpkin::Protocol::ListAudioFiles>() const {
  return payload_as_ListAudioFiles();
}

template<> inline const Pumpkin::Protocol::PlayAudioFile *ClientMessage::payload_as<Pumpkin::Protocol::PlayAudioFile>() const {
  return payload_as_PlayAudioFile();
}

template<> inline const Pumpkin::Protocol::BeginAudioUpload *ClientMessage::payload_as<Pumpkin::Protocol::BeginAudioUpload>() const {
  return payload_as_BeginAudioUpload();
}

template<> inline const Pumpkin::Protocol::AudioUploadChunk *ClientMessage::payload_as<Pumpkin::Protocol::AudioUploadChunk>() const {
  return payload_as_AudioUploadChunk();
}

template<> inline const Pumpkin::Protocol::FinishAudioUpload *ClientMessage::payload_as<Pumpkin::Protocol::FinishAudioUpload>() const {
  return payload_as_FinishAudioUpload();
}

template<> inline const Pumpkin::Protocol::CancelAudioUpload *ClientMessage::payload_as<Pumpkin::Protocol::CancelAudioUpload>() const {
  return payload_as_CancelAudioUpload();
}

struct ClientMessageBuilder {
  typedef ClientMessage Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_request_id(uint32_t request_id) {
    fbb_.AddElement<uint32_t>(ClientMessage::VT_REQUEST_ID, request_id, 0);
  }
  void add_payload_type(Pumpkin::Protocol::ClientPayload payload_type) {
    fbb_.AddElement<uint8_t>(ClientMessage::VT_PAYLOAD_TYPE, static_cast<uint8_t>(payload_type), 0);
  }
  void add_payload(::flatbuffers::Offset<void> payload) {
    fbb_.AddOffset(ClientMessage::VT_PAYLOAD, payload);
  }
  explicit ClientMessageBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientMessage> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientMessage>(end);
    fbb_.Required(o, ClientMessage::VT_PAYLOAD);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientMessage> CreateClientMessage(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t request_id = 0,
    Pumpkin::Protocol::ClientPayload payload_type = Pumpkin::Protocol::ClientPayload_NONE,
    ::flatbuffers::Offset<void> payload = 0) {
  ClientMessageBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_request_id(request_id);
  builder_.add_payload_type(payload_type);
  return builder_.Finish();
}

struct Success FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SuccessBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct SuccessBuilder {
  typedef Success Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit SuccessBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Success> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Success>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Success> CreateSuccess(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  SuccessBuilder builder_(_fbb);
  return builder_.Finish();
}

struct Error FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ErrorBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CODE = 4,
    VT_MESSAGE = 6
  };
  Pumpkin::Protocol::ErrorCode code() const {
    return static_cast<Pumpkin::Protocol::ErrorCode>(GetField<uint8_t>(VT_CODE, 0));
  }
  const ::flatbuffers::String *message() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MESSAGE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_CODE, 1) &&
           VerifyOffsetRequired(verifier, VT_MESSAGE) &&
           verifier.VerifyString(message()) &&
           verifier.EndTable();
  }
};

struct ErrorBuilder {
  typedef Error Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_code(Pumpkin::Protocol::ErrorCode code) {
    fbb_.AddElement<uint8_t>(Error::VT_CODE, static_cast<uint8_t>(code), 0);
  }
  void add_message(::flatbuffers::Offset<::flatbuffers::String> message) {
    fbb_.AddOffset(Error::VT_MESSAGE, message);
  }
  explicit ErrorBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Error> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Error>(end);
    fbb_.Required(o, Error::VT_MESSAGE);
    return o;
  }
};

inline ::flatbuffers::Offset<Error> CreateError(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    Pumpkin::Protocol::ErrorCode code = Pumpkin::Protocol::ErrorCode_UNKNOWN,
    ::flatbuffers::Offset<::flatbuffers::String> message = 0) {
  ErrorBuilder builder_(_fbb);
  builder_.add_message(message);
  builder_.add_code(code);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Error> CreateErrorDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    Pumpkin::Protocol::ErrorCode code = Pumpkin::Protocol::ErrorCode_UNKNOWN,
    const char *message = nullptr) {
  auto message__ = message ? _fbb.CreateString(message) : 0;
  return Pumpkin::Protocol::CreateError(
      _fbb,
      code,
      message__);
}

struct Volume FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef VolumeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUE = 4
  };
  float value() const {
    return GetField<float>(VT_VALUE, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_VALUE, 4) &&
           verifier.EndTable();
  }
};

struct VolumeBuilder {
  typedef Volume Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_value(float value) {
    fbb_.AddElement<float>(Volume::VT_VALUE, value, 0.0f);
  }
  explicit VolumeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Volume> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Volume>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Volume> CreateVolume(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float value = 0.0f) {
  VolumeBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

struct AudioFile FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AudioFileBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_SIZE = 6
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  uint32_t size() const {
    return GetField<uint32_t>(VT_SIZE, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<uint32_t>(verifier, VT_SIZE, 4) &&
           verifier.EndTable();
  }
};

struct AudioFileBuilder {
  typedef AudioFile Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(AudioFile::VT_NAME, name);
  }
  void add_size(uint32_t size) {
    fbb_.AddElement<uint32_t>(AudioFile::VT_SIZE, size, 0);
  }
  explicit AudioFileBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AudioFile> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AudioFile>(end);
    fbb_.Required(o, AudioFile::VT_NAME);
    return o;
  }
};

inline ::flatbuffers::Offset<AudioFile> CreateAudioFile(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    uint32_t size = 0) {
  AudioFileBuilder builder_(_fbb);
  builder_.add_size(size);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<AudioFile> CreateAudioFileDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    uint32_t size = 0) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return Pumpkin::Protocol::CreateAudioFile(
      _fbb,
      name__,
      size);
}

struct AudioFileList FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AudioFileListBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FILES = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<Pumpkin::Protocol::AudioFile>> *files() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Pumpkin::Protocol::AudioFile>> *>(VT_FILES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_FILES) &&
           verifier.VerifyVector(files()) &&
           verifier.VerifyVectorOfTables(files()) &&
           verifier.EndTable();
  }
};

struct AudioFileListBuilder {
  typedef AudioFileList Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_files(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Pumpkin::Protocol::AudioFile>>> files) {
    fbb_.AddOffset(AudioFileList::VT_FILES, files);
  }
  explicit AudioFileListBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AudioFileList> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AudioFileList>(end);
    fbb_.Required(o, AudioFileList::VT_FILES);
    return o;
  }
};

inline ::flatbuffers::Offset<AudioFileList> CreateAudioFileList(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Pumpkin::Protocol::AudioFile>>> files = 0) {
  AudioFileListBuilder builder_(_fbb);
  builder_.add_files(files);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<AudioFileList> CreateAudioFileListDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<Pumpkin::Protocol::AudioFile>> *files = nullptr) {
  auto files__ = files ? _fbb.CreateVector<::flatbuffers::Offset<Pumpkin::Protocol::AudioFile>>(*files) : 0;
  return Pumpkin::Protocol::CreateAudioFileList(
      _fbb,
      files__);
}

struct ServerMessage FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ServerMessageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_REQUEST_ID = 4,
    VT_PAYLOAD_TYPE = 6,
    VT_PAYLOAD = 8
  };
  uint32_t request_id() const {
    return GetField<uint32_t>(VT_REQUEST_ID, 0);
  }
  Pumpkin::Protocol::ServerPayload payload_type() const {
    return static_cast<Pumpkin::Protocol::ServerPayload>(GetField<uint8_t>(VT_PAYLOAD_TYPE, 0));
  }
  const void *payload() const {
    return GetPointer<const void *>(VT_PAYLOAD);
  }
  template<typename T> const T *payload_as() const;
  const Pumpkin::Protocol::Success *payload_as_Success() const {
    return payload_type() == Pumpkin::Protocol::ServerPayload_Success ? static_cast<const Pumpkin::Protocol::Success *>(payload()) : nullptr;
  }
  const Pumpkin::Protocol::Error *payload_as_Error() const {
    return payload_type() == Pumpkin::Protocol::ServerPayload_Error ? static_cast<const Pumpkin::Protocol::Error *>(payload()) : nullptr;
  }
  const Pumpkin::Protocol::Volume *payload_as_Volume() const {
    return payload_type() == Pumpkin::Protocol::ServerPayload_Volume ? static_cast<const Pumpkin::Protocol::Volume *>(payload()) : nullptr;
  }
  const Pumpkin::Protocol::AudioFileList *payload_as_AudioFileList() const {
    return payload_type() == Pumpkin::Protocol::ServerPayload_AudioFileList ? static_cast<const Pumpkin::Protocol::AudioFileList *>(payload()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_REQUEST_ID, 4) &&
           VerifyField<uint8_t>(verifier, VT_PAYLOAD_TYPE, 1) &&
           VerifyOffsetRequired(verifier, VT_PAYLOAD) &&
           VerifyServerPayload(verifier, payload(), payload_type()) &&
           verifier.EndTable();
  }
};

template<> inline const Pumpkin::Protocol::Success *ServerMessage::payload_as<Pumpkin::Protocol::Success>() const {
  return payload_as_Success();
}

template<> inline const Pumpkin::Protocol::Error *ServerMessage::payload_as<Pumpkin::Protocol::Error>() const {
  return payload_as_Error();
}

template<> inline const Pumpkin::Protocol::Volume *ServerMessage::payload_as<Pumpkin::Protocol::Volume>() const {
  return payload_as_Volume();
}

template<> inline const Pumpkin::Protocol::AudioFileList *ServerMessage::payload_as<Pumpkin::Protocol::AudioFileList>() const {
  return payload_as_AudioFileList();
}

struct ServerMessageBuilder {
  typedef ServerMessage Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_request_id(uint32_t request_id) {
    fbb_.AddElement<uint32_t>(ServerMessage::VT_REQUEST_ID, request_id, 0);
  }
  void add_payload_type(Pumpkin::Protocol::ServerPayload payload_type) {
    fbb_.AddElement<uint8_t>(ServerMessage::VT_PAYLOAD_TYPE, static_cast<uint8_t>(payload_type), 0);
  }
  void add_payload(::flatbuffers::Offset<void> payload) {
    fbb_.AddOffset(ServerMessage::VT_PAYLOAD, payload);
  }
  explicit ServerMessageBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ServerMessage> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ServerMessage>(end);
    fbb_.Required(o, ServerMessage::VT_PAYLOAD);
    return o;
  }
};

inline ::flatbuffers::Offset<ServerMessage> CreateServerMessage(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t request_id = 0,
    Pumpkin::Protocol::ServerPayload payload_type = Pumpkin::Protocol::ServerPayload_NONE,
    ::flatbuffers::Offset<void> payload = 0) {
  ServerMessageBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_request_id(request_id);
  builder_.add_payload_type(payload_type);
  return builder_.Finish();
}

struct Message FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MessageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BODY_TYPE = 4,
    VT_BODY = 6
  };
  Pumpkin::Protocol::MessageBody body_type() const {
    return static_cast<Pumpkin::Protocol::MessageBody>(GetField<uint8_t>(VT_BODY_TYPE, 0));
  }
  const void *body() const {
    return GetPointer<const void *>(VT_BODY);
  }
  template<typename T> const T *body_as() const;
  const Pumpkin::Protocol::ClientMessage *body_as_ClientMessage() const {
    return body_type() == Pumpkin::Protocol::MessageBody_ClientMessage ? static_cast<const Pumpkin::Protocol::ClientMessage *>(body()) : nullptr;
  }
  const Pumpkin::Protocol::ServerMessage *body_as_ServerMessage() const {
    return body_type() == Pumpkin::Protocol::MessageBody_ServerMessage ? static_cast<const Pumpkin::Protocol::ServerMessage *>(body()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_BODY_TYPE, 1) &&
           VerifyOffsetRequired(verifier, VT_BODY) &&
           VerifyMessageBody(verifier, body(), body_type()) &&
           verifier.EndTable();
  }
};

template<> inline const Pumpkin::Protocol::ClientMessage *Message::body_as<Pumpkin::Protocol::ClientMessage>() const {
  return body_as_ClientMessage();
}

template<> inline const Pumpkin::Protocol::ServerMessage *Message::body_as<Pumpkin::Protocol::ServerMessage>() const {
  return body_as_ServerMessage();
}

struct MessageBuilder {
  typedef Message Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_body_type(Pumpkin::Protocol::MessageBody body_type) {
    fbb_.AddElement<uint8_t>(Message::VT_BODY_TYPE, static_cast<uint8_t>(body_type), 0);
  }
  void add_body(::flatbuffers::Offset<void> body) {
    fbb_.AddOffset(Message::VT_BODY, body);
  }
  explicit MessageBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Message> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Message>(end);
    fbb_.Required(o, Message::VT_BODY);
    return o;
  }
};

inline ::flatbuffers::Offset<Message> CreateMessage(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    Pumpkin::Protocol::MessageBody body_type = Pumpkin::Protocol::MessageBody_NONE,
    ::flatbuffers::Offset<void> body = 0) {
  MessageBuilder builder_(_fbb);
  builder_.add_body(body);
  builder_.add_body_type(body_type);
  return builder_.Finish();
}

inline bool VerifyClientPayload(::flatbuffers::Verifier &verifier, const void *obj, ClientPayload type) {
  switch (type) {
    case ClientPayload_NONE: {
      return true;
    }
    case ClientPayload_StartAudioStream: {
      auto ptr = reinterpret_cast<const Pumpkin::Protocol::StartAudioStream *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ClientPayload_StopAudioStream: {
      auto ptr = reinterpret_cast<const Pumpkin::Protocol::StopAudioStream *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ClientPayload_PlayShow: {
      auto ptr = reinterpret_cast<const Pumpkin::Protocol::PlayShow *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ClientPayload_AudioChunk: {
      auto ptr = reinterpret_cast<const Pumpkin::Protocol::AudioChunk *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ClientPayload_ResetAudio: {
      auto ptr = reinterpret_cast<const Pumpkin::Protocol::ResetAudio *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ClientPayload_GetVolume: {
      auto ptr = reinterpret_cast<const Pumpkin::Protocol::GetVolume *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ClientPayload_AdjustVolume: {
      auto ptr = reinterpret_cast<const Pumpkin::Protocol::AdjustVolume *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ClientPayload_ListAudioFiles: {
      auto ptr = reinterpret_cast<const Pumpkin::Protocol::ListAudioFiles *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ClientPayload_PlayAudioFile: {
      auto ptr = reinterpret_cast<const Pumpkin::Protocol::PlayAudioFile *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ClientPayload_BeginAudioUpload: {
      auto ptr = reinterpret_cast<const Pumpkin::Protocol::BeginAudioUpload *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ClientPayload_AudioUploadChunk: {
      auto ptr = reinterpret_cast<const Pumpkin::Protocol::AudioUploadChunk *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ClientPayload_FinishAudioUpload: {
      auto ptr = reinterpret_cast<const Pumpkin::Protocol::FinishAudioUpload *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ClientPayload_CancelAudioUpload: {
      auto ptr = reinterpret_cast<const Pumpkin::Protocol::CancelAudioUpload *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyClientPayloadVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyClientPayload(
        verifier,  values->Get(i), types->GetEnum<ClientPayload>(i))) {
      return false;
    }
  }
  return true;
}

inline bool VerifyServerPayload(::flatbuffers::Verifier &verifier, const void *obj, ServerPayload type) {
  switch (type) {
    case ServerPayload_NONE: {
      return true;
    }
    case ServerPayload_Success: {
      auto ptr = reinterpret_cast<const Pumpkin::Protocol::Success *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ServerPayload_Error: {
      auto ptr = reinterpret_cast<const Pumpkin::Protocol::Error *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ServerPayload_Volume: {
      auto ptr = reinterpret_cast<const Pumpkin::Protocol::Volume *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ServerPayload_AudioFileList: {
      auto ptr = reinterpret_cast<const Pumpkin::Protocol::AudioFileList *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyServerPayloadVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyServerPayload(
        verifier,  values->Get(i), types->GetEnum<ServerPayload>(i))) {
      return false;
    }
  }
  return true;
}

inline bool VerifyMessageBody(::flatbuffers::Verifier &verifier, const void *obj, MessageBody type) {
  switch (type) {
    case MessageBody_NONE: {
      return true;
    }
    case MessageBody_ClientMessage: {
      auto ptr = reinterpret_cast<const Pumpkin::Protocol::ClientMessage *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MessageBody_ServerMessage: {
      auto ptr = reinterpret_cast<const Pumpkin::Protocol::ServerMessage *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyMessageBodyVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyMessageBody(
        verifier,  values->Get(i), types->GetEnum<MessageBody>(i))) {
      return false;
    }
  }
  return true;
}

inline const Pumpkin::Protocol::Message *GetMessage(const void *buf) {
  return ::flatbuffers::GetRoot<Pumpkin::Protocol::Message>(buf);
}

inline const Pumpkin::Protocol::Message *GetSizePrefixedMessage(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Pumpkin::Protocol::Message>(buf);
}

inline const char *MessageIdentifier() {
  return "PKIN";
}

inline bool MessageBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, MessageIdentifier());
}

inline bool SizePrefixedMessageBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, MessageIdentifier(), true);
}

inline bool VerifyMessageBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Pumpkin::Protocol::Message>(MessageIdentifier());
}

inline bool VerifySizePrefixedMessageBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Pumpkin::Protocol::Message>(MessageIdentifier());
}

inline void FinishMessageBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Pumpkin::Protocol::Message> root) {
  fbb.Finish(root, MessageIdentifier());
}

inline void FinishSizePrefixedMessageBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Pumpkin::Protocol::Message> root) {
  fbb.FinishSizePrefixed(root, MessageIdentifier());
}

}  // namespace Protocol
}  // namespace Pumpkin

#endif  // FLATBUFFERS_GENERATED_PUMPKIN_PUMPKIN_PROTOCOL_H_
