name: Build PlatformIO project

on:
  push:
    branches: main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  detect-envs:
    runs-on: ubuntu-latest
    outputs:
      environments: ${{ steps.get-envs.outputs.environments }}
    steps:
      - uses: actions/checkout@v7
      - id: get-envs
        run: |
          envs=$(grep -oP '(?<=^\[env:)[^\]]+' platformio.ini | jq -Rsc 'split("\n") | map(select(. != ""))')
          echo "environments=$envs" >> "$GITHUB_OUTPUT"

  build:
    needs: detect-envs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: ${{ fromJson(needs.detect-envs.outputs.environments) }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/cache@v6
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build ${{ matrix.environment }}
        run: pio run -e ${{ matrix.environment }}
